### ISSUE TITLE
Error: Command failed: pod repo update

### ISSUE THREAD

**Issue by DevMinhThu** [SpQuyt/amela-rn-cli#16]
When I installed the CLI I got the following error. 
But when building the project still works. 
It's just that the project doesn't split the development environments.

![image](https://user-images.githubusercontent.com/51977303/196092776-e497695b-b1aa-4448-897f-5957c95f88b1.png)

**Comment by SpQuyt** [comment]
Seems like it's a bug of Updating Pod in Mac Apple M1 Chip.
It is mentioned here in react-native website.
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/17812909/196329723-5b214725-208e-4240-8d84-ef9cf8329c28.png">

I will find out a way so that this CLI can detect M1 Environment. Thank you!

**Comment by SpQuyt** [comment]
@DevMinhThu 
I found a solutions that you should remove and reinstall Cocoapods. Please try this solution and reply me.
<img width="615" alt="image" src="https://user-images.githubusercontent.com/17812909/198196114-ec7c57ea-32d8-4278-9816-88a1ca5965cb.png">
